language: python
matrix:
  include:
  - python: '2.7'
    env: DJANGO_VERSION=1.11.11
  - python: '3.6'
    env: DJANGO_VERSION=2.1.5
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install flake8
  - python setup.py install
script:
  - flake8 django_query_debug tests
  - python setup.py test
after_success:
  - pip install python-coveralls
  - coveralls