language: python
matrix:
  include:
  - python: '2.7'
    env: DJANGO_VERSION=1.11.11
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py install
script:
  - flake8
  - python setup.py test